---
title: "Untitled"
author: "Yuqi Miao ym2771"
date: "5/8/2020"
output: html_document
---

# 2 Methods

## 2.1 Bayesian model for hurricane trajectories. 

Climate researchers are interested in modeling the hurricane trajectories. Let $t$ be time (in hours) since a hurricane began, and For each hurrican $i$, we denote 
$\{ Y_{i,1}(t), Y_{i,2}(t), Y_{i,3}(t)\},j=1,2,3$ be the latitude, longitude, and wind speed at time $t$. The following Baysian model was suggested.

$$Y_{i,j}(t+6) =  \mu_{i,j}(t) +\rho_jY_{i,j}(t) + \epsilon_{i,j}(t)$$
where $\mu_{i,j}(t)$ is the funtional mean, and the errors $(\epsilon_{i,1}(t),\epsilon_{i,2}(t),\epsilon_{i,3}(t))$ follows a multivariate normal distributions with mean zero and covariance matrix $\Sigma$, independent across $t$. We further assume that the mean functions $\mu_{i,j}(t)$ can be written as
$$\mu_{i,j}(t) =  \beta_{0,j}+x_{i,1}(t)\beta_{1,j} +
x_{i,2} \beta_{2,j} + x_{i,3}\beta_{3,j} +
\sum_{k=1}^3\beta_{3+k,j}\Delta_{i,k}(t-6)
$$ where
$x_{i,1}(t)$, ranging from 0 to 365, is the day of year at time $t$, $x_{i,2}$ is the calenda year of the hurrican, and $x_{i,3}$ is the type of hurrican, 
and
$$\Delta_{i,k}(t-6) = Y_{i,k}(t) -Y_{i,k}(t-6),k=1,2,3$$

We assume the following prior distributions:

For $\boldsymbol{\beta}=(\beta_{k,j})_{k=0,...,6, j=1,2,3}$, we assume
$\pi(\boldsymbol{\beta})$ is jointly normal with mean 0 and variance $diag(1, p)$. 

We assume that $\pi(\rho_j)$ follows a trucated normal  $N_{[0,1]}(0.5, 1/5)$ 
 
 $\pi(\Sigma^{-1})$ follows a $Wishart (3, diag(0.1,3))$
 

## 2.2 Posterior likelihood building

We assume the data follows multi-variate normal distribution
$$\begin{pmatrix}Y_{i,1}(t+6)\\Y_{i,2}(t+6)\\Y_{i,3}(t+6)\end{pmatrix}\sim MVN\begin{pmatrix}Y_{i,1}(t)&\\Y_{i,2}(t)&,\Sigma\\Y_{i,3}(t)\end{pmatrix}$$
 
Here we assuming the data points are independently identically distributed, where the likelihood is  the multiplication of the point likelihoods
 
The posterior distribution for parameters is given by:

$$\pi(\theta|y) \propto L(y|\theta)*\pi(\beta)*\pi(\rho)*\pi(\Sigma^{-1})$$
 
## 2.3 Metropolis-Hasting algorithm for parameter estimation

To estimate parameters in posterior distribution, we decide by following rule: 

For t the iteration, we use multi-variate normal as convenient conditional distribution to draw candidate samples $\boldsymbol {\theta^{(t+1)}}$, and geenerate U from uniform distribution in [0,1],

$$if \;U < \alpha = min\{1, \frac{q(\boldsymbol {\theta^{(t)}}|\boldsymbol {\theta^{(t+1)}})\pi(\boldsymbol {\theta^{(t+1)}}|\boldsymbol {y})}{q(\boldsymbol {\theta^{(t+1)}}|\boldsymbol {\theta^{(t)}})\pi(\boldsymbol {\theta^{(t)}}|\boldsymbol {y})}\}$$
we accept $\boldsymbol {\theta^{(t+1)}}$, else we take $\boldsymbol {\theta^{(t)}}$ as $\boldsymbol {\theta^{(t+1)}}$
 
 
 
 
 
 
 
 
 
 
 
 
 
 